# Generated by Django 5.1.6 on 2025-02-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='e', max_length=40),
            preserve_default=False,
        ),
    ]
